spring:
  kafka:
    bootstrap-servers: localhost:9092

    streams:
      application-id: kafka-streams-lab4-v10

      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        auto.offset.reset: earliest